<?php


/**
 * Implements hook_api_tokens_info().
 */
function api_token_provider_api_tokens_info() {
  $tokens = array();

  $tokens['date'] = array(
    'title' => t('Date'),
    //'handler' => 'api_token_provider_handle_date',
    // no sense to cache lightweight or dynamic handlers
    //'cache' => FALSE,
  );

  $tokens['user-link'] = array(
    'title' => t('User Link'),
    'handler' => 'api_token_provider_handle_user_link',
    'inc' => 'includes/api_tokens',
    // no sense to cache lightweight or dynamic handlers
    'cache' => DRUPAL_CACHE_PER_USER,
  );

  $tokens['node-list'] = array(
    'title' => t('Node List'),
    //'handler' => 'api_token_provider_handle_user_link',
    'inc' => 'includes/api_tokens',
    'cache' => DRUPAL_CACHE_GLOBAL,
    'cache_expire' => 300,
  );

  $tokens['test-token'] = array(
    'title' => t('Test Token'),
    'inc' => 'includes/api_tokens',
    'cache' => DRUPAL_CACHE_PER_PAGE | DRUPAL_CACHE_PER_ROLE | DRUPAL_CACHE_PER_USER | DRUPAL_CACHE_GLOBAL,
    'cache_expire' => 10,
  );

  return $tokens;
}


/**
 * Defines date API tokens handler.
 */
function api_token_provider_apitoken_date() {
  $output = '<strong>' . date('c') . '</strong>';

  return $output;
}
