<?php


/**
 * Implements hook_api_tokens_info().
 */
function api_token_provider_api_tokens_info() {
  $tokens = array();

  $tokens['api_token_provider_date'] = array(
    'title' => t('Date'),
    'handler' => 'api_token_provider_handle_date',
    'inc' => '',
    // no sense to cache lightweight handlers
    'cache' => FALSE,
  );

  return $tokens;
}


/**
 * Defines date API tokens handler.
 */
function api_token_provider_handle_date() {
  $output = '<strong>' . date('c') . '</strong>';

  return $output;
}
